### ISSUE TITLE
Grant S3 Permissions Missing s3:ListBucket For Bucket ARN

### ISSUE THREAD

**Issue by msidwell** [meadowdata/meadowrun#121]
The Meadowrun generated EC2 Role policy from ```meadowrun-manage-ec2 grant-permission-to-s3-bucket``` only covers ```*Object``` actions against ```arn:aws:s3:::bucket-name/*``` which will cause boto3 to fail when attempting to list objects in the bucket (i.e. for Dalle model caching). This can be resolved by adding the ```ListBucket``` action against the actual bucket resource ARN as ```arn:aws:s3:::bucket-name``` into the policy statement.

Example ListObjects error from bot3 below:

```
Traceback (most recent call last):
  File "/meadowrun/code0/backend/app.py", line 67, in <module>
    dalle_model = DalleModel(args.model_version, args.s3_bucket, args.s3_bucket_region)
  File "/meadowrun/code0/backend/dalle_model.py", line 63, in __init__
    dalle_model = download_pretrained_model_from_s3(str(model_version), s3_bucket, s3_bucket_region)
  File "/meadowrun/code0/backend/cache_in_s3.py", line 38, in download_pretrained_model_from_s3
    for file in s3.list_objects(Bucket=s3_bucket)["Contents"]:
  File "/usr/local/lib/python3.9/dist-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/dist-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied
```

**Comment by hrichardlee** [comment]
Thank you for the suggestion! Just made the change.

I assume you know how to work around this for now by just manually modifying the generated IAM policy
