### ISSUE TITLE
Test failures: unknown opcode

### ISSUE THREAD

**Issue by kurtschelfthout** [meadowdata/meadowrun#218]
Getting "unknown opcode" (???) on latest main in `test_pip_file_in_git_repo_with_data_file` and `test_local_pip_file_with_data_file` 

Both in local and aws tests (haven't tried others).

```
/tests/automated/test_local_automated.py::TestBasicsLocal::test_pip_file_in_git_repo_with_data_file Failed: [undefined]meadowrun.run_job_core.MeadowrunException: Failure while running a Meadowrun job: PYTHON_EXCEPTION
Log file: /tmp/pytest-of-kurts/pytest-5/test_pip_file_in_git_repo_with0/job_logs/remote_function.19c27f4b-d5d5-4a44-a3d4-d7a7665a1f15.log
Traceback (most recent call last):
  File "/meadowrun/code__meadowrun_func_worker.py", line 74, in main
    result = function(*(function_args or ()), **(function_kwargs or {}))
  File "/home/kurts/projects/meadowrun/tests/basics.py", line 328, in remote_function
SystemError: unknown opcode
self = <automated.test_local_automated.TestBasicsLocal object at 0x7f7a9b39a850>

    @pytest.mark.skipif("sys.version_info < (3, 8)")
    @pytest.mark.asyncio
    async def test_pip_file_in_git_repo_with_data_file(self) -> None:
        """This test is doing double-duty, also checking for the machine_cache folder"""
    
        # TODO upgrade the Meadowrun referenced in requirements.txt and move this inside
        # remote_function
        machine_cache_folder = meadowrun.MACHINE_CACHE_FOLDER
    
        def remote_function() -> str:
            # make sure the machine cache folder is writable
            with open(
                os.path.join(machine_cache_folder, "foo"), "w", encoding="utf-8"
            ) as f:
                f.write("test")
    
            with open("example_package/test.txt", encoding="utf-8") as f:
                return f.read()
    
>       results = await run_function(
            remote_function,
            self.get_host(),
            self.get_resources_required(),
            Deployment.git_repo(
                repo_url=self.get_test_repo_url(),
                interpreter=PipRequirementsFile("requirements.txt", "3.9"),
            ),
        )

tests/basics.py:333: 
```

**Comment by kurtschelfthout** [comment]
probably because I was using py3.8 to py3.9
